version: '3'

services:
  mongodb:
    build:
      context: .
      dockerfile: Dockerfile  
    container_name: mongoContainer
    networks:
      - my_network
    #restart: unless-stopped
    ports:
      - "27018:27017"
    volumes:
      - mongoChatAppData:/data/db

networks:
  my_network:
    driver: bridge

volumes:
  mongoChatAppData:
